Repository turt1eRun/turtle-run, pull requests merged in 2024-10, with the labels that each got.

#5 [Feat] Inquiry 엔티티 추가
  src/main/java/trend_setter/turtlerun/inquiry/entity/Inquiry.java
  src/main/java/trend_setter/turtlerun/inquiry/entity/InquiryStatus.java
  src/main/java/trend_setter/turtlerun/inquiry/entity/InquriyResponse.java
Labels: enhancement

#8 [Feat] FAQ 엔티티 추가
  src/main/java/trend_setter/turtlerun/inquiry/entity/Faq.java
Labels: enhancement

#10 [Bug] 문의 엔티티 1차 수정
  src/main/java/trend_setter/turtlerun/inquiry/entity/Faq.java
  src/main/java/trend_setter/turtlerun/inquiry/entity/Inquiry.java
  src/main/java/trend_setter/turtlerun/inquiry/entity/InquiryResponse.java
  src/main/java/trend_setter/turtlerun/inquiry/entity/InquiryStatus.java
  src/main/java/trend_setter/turtlerun/inquiry/entity/InquriyResponse.java
Labels: bug

#14 [Feat] 문의 관련 엔티티 디폴트 생성자 어노테이션으로 정의
  src/main/java/trend_setter/turtlerun/inquiry/entity/Faq.java
  src/main/java/trend_setter/turtlerun/inquiry/entity/Inquiry.java
  src/main/java/trend_setter/turtlerun/inquiry/entity/InquiryResponse.java
  src/main/java/trend_setter/turtlerun/inquiry/entity/InquiryStatus.java
Labels: 🔨 Refactor

#21 [Bug] Charge, Donation, Refund 초기 Status 값 수정
  src/main/java/trend_setter/turtlerun/wallet/entity/Charge.java
  src/main/java/trend_setter/turtlerun/wallet/entity/Donation.java
  src/main/java/trend_setter/turtlerun/wallet/entity/Refund.java
Labels: 🐛 Bug Fix

#26 [Feat] Subscription 엔티티 추가
  src/main/java/trend_setter/turtlerun/subscription/entity/Subscription.java
Labels: ✨ Feature

#28 [Feat] Like 엔티티 추가
  src/main/java/trend_setter/turtlerun/like/entity/Like.java
Labels: ✨ Feature

#30 [Feat] Notification 관련 엔티티 추가
  src/main/java/trend_setter/turtlerun/notification/entity/Notification.java
  src/main/java/trend_setter/turtlerun/notification/entity/NotificationReceipt.java
  src/main/java/trend_setter/turtlerun/notification/entity/NotificationSetting.java
  src/main/java/trend_setter/turtlerun/notification/entity/NotificationType.java
Labels: ✨ Feature

#38 [Feat] 문의하기 기능 1차 구현
  src/main/java/trend_setter/turtlerun/inquiry/controller/InquiryController.java
  src/main/java/trend_setter/turtlerun/inquiry/dto/InquiryDetailDto.java
  src/main/java/trend_setter/turtlerun/inquiry/dto/InquiryListDto.java
  src/main/java/trend_setter/turtlerun/inquiry/dto/InquiryWriteDto.java
  src/main/java/trend_setter/turtlerun/inquiry/repository/InquiryRepository.java
  src/main/java/trend_setter/turtlerun/inquiry/service/InquiryService.java
  src/main/java/trend_setter/turtlerun/inquiry/utils/InquiryMapper.java
Labels: ✨ Feature

#39 [Feat] 리액트 패키지 추가
  frontend/.gitignore
  frontend/README.md
  frontend/package-lock.json
  frontend/package.json
  frontend/public/favicon.ico
  frontend/public/index.html
  frontend/public/logo192.png
  frontend/public/logo512.png
  frontend/public/manifest.json
  frontend/public/robots.txt
  frontend/src/App.css
  frontend/src/App.js
  frontend/src/App.test.js
  frontend/src/index.css
  frontend/src/index.js
  frontend/src/logo.svg
  frontend/src/reportWebVitals.js
  frontend/src/setProxy.js
  frontend/src/setupTests.js
Labels: ✨ Feature

#43 [Feat] React(CRA) -> Next.js + TypeScript 변경
  frontend/.eslintrc.json
  frontend/.gitignore
  frontend/README.md
  frontend/next.config.ts
  frontend/package-lock.json
  frontend/package.json
  frontend/postcss.config.mjs
  frontend/public/favicon.ico
  frontend/public/file.svg
  frontend/public/globe.svg
  frontend/public/index.html
  frontend/public/logo192.png
  frontend/public/logo512.png
  frontend/public/manifest.json
  frontend/public/next.svg
  frontend/public/robots.txt
  frontend/public/vercel.svg
  frontend/public/window.svg
  frontend/src/App.css
  frontend/src/App.js
  frontend/src/App.test.js
  frontend/src/app/favicon.ico
  frontend/src/app/fonts/GeistMonoVF.woff
  frontend/src/app/fonts/GeistVF.woff
  frontend/src/app/globals.css
  frontend/src/app/layout.tsx
  frontend/src/app/page.tsx
  frontend/src/index.css
  frontend/src/index.js
  frontend/src/logo.svg
  frontend/src/reportWebVitals.js
  frontend/src/setProxy.js
  frontend/src/setupTests.js
  frontend/tailwind.config.ts
  frontend/tsconfig.json
Labels: ✨ Feature

#44 [Feat] 신고 엔티티 추가
  src/main/java/trend_setter/turtlerun/report/constant/ReportStatus.java
  src/main/java/trend_setter/turtlerun/report/constant/ReportType.java
  src/main/java/trend_setter/turtlerun/report/entity/ConnectionReport.java
  src/main/java/trend_setter/turtlerun/report/entity/ContentReport.java
  src/main/java/trend_setter/turtlerun/report/entity/ReportHistory.java
  src/main/java/trend_setter/turtlerun/report/entity/ReportReason.java
Labels: ✨ Feature

#46 [Feat] Wallet 엔티티 제거
  src/main/java/trend_setter/turtlerun/wallet/entity/Charge.java
  src/main/java/trend_setter/turtlerun/wallet/entity/Donation.java
  src/main/java/trend_setter/turtlerun/wallet/entity/Refund.java
  src/main/java/trend_setter/turtlerun/wallet/entity/RefundType.java
  src/main/java/trend_setter/turtlerun/wallet/entity/TransactionStatus.java
  src/main/java/trend_setter/turtlerun/wallet/entity/TransactionType.java
  src/main/java/trend_setter/turtlerun/wallet/entity/Wallet.java
  src/main/java/trend_setter/turtlerun/wallet/entity/WalletHistory.java
Labels: ✨ Feature

#54 [Feat] 회원가입 기능, 로그인 기능 구현
  src/main/java/trend_setter/turtlerun/global/config/SecurityConfig.java
  src/main/java/trend_setter/turtlerun/user/constant/Role.java
  src/main/java/trend_setter/turtlerun/user/controller/UserController.java
  src/main/java/trend_setter/turtlerun/user/dto/LoginRequest.java
  src/main/java/trend_setter/turtlerun/user/dto/LoginResponse.java
  src/main/java/trend_setter/turtlerun/user/dto/RegisterUserRequest.java
  src/main/java/trend_setter/turtlerun/user/entity/User.java
  src/main/java/trend_setter/turtlerun/user/jwt/JwtTokenProvider.java
  src/main/java/trend_setter/turtlerun/user/jwt/JwtUtils.java
  src/main/java/trend_setter/turtlerun/user/repository/UserRepository.java
  src/main/java/trend_setter/turtlerun/user/service/UserService.java
Labels: ✨ Feature

#56 [Feat] 문의하기 기능 3차 구현
  src/main/java/trend_setter/turtlerun/global/config/SecurityConfig.java
  src/main/java/trend_setter/turtlerun/inquiry/controller/InquiryController.java
  src/main/java/trend_setter/turtlerun/inquiry/entity/Faq.java
  src/main/java/trend_setter/turtlerun/inquiry/entity/Inquiry.java
  src/main/java/trend_setter/turtlerun/inquiry/entity/InquiryResponse.java
  src/main/java/trend_setter/turtlerun/inquiry/repository/InquiryRepository.java
  src/main/java/trend_setter/turtlerun/inquiry/service/InquiryService.java
  src/main/java/trend_setter/turtlerun/inquiry/utils/InquiryMapper.java
  src/main/java/trend_setter/turtlerun/inquiry/utils/InquiryResponseMapper.java
  src/main/java/trend_setter/turtlerun/user/repository/UserRepository.java
Labels: ✨ Feature, 🔨 Refactor

#60 [Feat] Inquiry 기능 리팩토링
  src/main/java/trend_setter/turtlerun/inquiry/controller/InquiryController.java
  src/main/java/trend_setter/turtlerun/inquiry/dto/InquiryDetailDto.java
  src/main/java/trend_setter/turtlerun/inquiry/dto/InquiryResponseDto.java
  src/main/java/trend_setter/turtlerun/inquiry/dto/InquiryWriteDto.java
  src/main/java/trend_setter/turtlerun/inquiry/service/InquiryService.java
  src/main/java/trend_setter/turtlerun/inquiry/utils/InquiryMapper.java
  src/main/java/trend_setter/turtlerun/inquiry/utils/InquiryResponseMapper.java
  src/main/java/trend_setter/turtlerun/user/repository/UserRepository.java
Labels: 🔨 Refactor, ⚙️ BE
