Repository turt1eRun/turtle-run, pull requests merged in 2024-11, with the labels that each got.

#62 [Feat] Inquiry 기능 리팩토링
  src/main/java/trend_setter/turtlerun/inquiry/controller/InquiryController.java
  src/main/java/trend_setter/turtlerun/inquiry/repository/InquiryRepository.java
  src/main/java/trend_setter/turtlerun/inquiry/service/InquiryService.java
Labels: 🔨 Refactor, ⚙️ BE

#64 [Feat] 메인페이지 구현
  frontend/README.md
  frontend/package-lock.json
  frontend/package.json
  frontend/public/favicon.ico
  frontend/public/fonts/PretendardVariable.woff2
  frontend/public/images/logo.png
  frontend/src/app/(main)/layout.tsx
  frontend/src/app/(main)/page.tsx
  frontend/src/app/favicon.ico
  frontend/src/app/fonts/GeistMonoVF.woff
  frontend/src/app/fonts/GeistVF.woff
  frontend/src/app/layout.tsx
  frontend/src/app/login/layout.tsx
  frontend/src/app/login/page.tsx
  frontend/src/app/page.tsx
  frontend/src/components/common/Header.tsx
  frontend/src/components/common/Sidebar.tsx
  frontend/src/components/common/SidebarSimple.tsx
  frontend/src/lib/fonts.ts
  frontend/src/store/sidebarStore.ts
  frontend/src/styles/globals.css
  frontend/tailwind.config.ts
Labels: ✨ Feature, 💄 FE

#67 [Feat] CI/CD 구현
  frontend/.gitignore
  frontend/Dockerfile
  frontend/next.config.ts
  frontend/nginx/default.conf
  frontend/src/app/layout.tsx
  frontend/src/app/login/layout.tsx
  frontend/src/components/common/Header.tsx
Labels: 🔄 CI/CD

#68 [Bug] User import 경로 수정
  src/main/java/trend_setter/turtlerun/report/entity/ConnectionReport.java
  src/main/java/trend_setter/turtlerun/report/entity/ContentReport.java
  src/main/java/trend_setter/turtlerun/report/entity/ReportHistory.java
Labels: 🐛 Bug Fix, ⚙️ BE

#70 refactor: 패키지 구조에 맞게 엔티티 경로 수정
  src/main/java/trend_setter/turtlerun/like/entity/Like.java
  src/main/java/trend_setter/turtlerun/notification/entity/Notification.java
  src/main/java/trend_setter/turtlerun/notification/entity/NotificationSetting.java
  src/main/java/trend_setter/turtlerun/subscription/entity/Subscription.java
Labels: 🔨 Refactor, ⚙️ BE

#79 [Bug] CI/CD 배포 코드 변경
  .github/workflows/deploy.yml
Labels: 🔄 CI/CD

#82 [Bug] CI/CD 배포 paths 수정
  .github/workflows/deploy.yml
Labels: 🐛 Bug Fix

#85 [Refactor] JWT 인증 방식 적용
  build.gradle
  src/main/java/trend_setter/turtlerun/global/config/SecurityConfig.java
  src/main/java/trend_setter/turtlerun/user/controller/UserController.java
  src/main/java/trend_setter/turtlerun/user/dto/UserResponseDto.java
  src/main/java/trend_setter/turtlerun/user/entity/User.java
  src/main/java/trend_setter/turtlerun/user/jwt/CustomHttpServletRequestWrapper.java
  src/main/java/trend_setter/turtlerun/user/jwt/JwtAuthenticationFilter.java
  src/main/java/trend_setter/turtlerun/user/jwt/JwtTokenProvider.java
  src/main/java/trend_setter/turtlerun/user/jwt/JwtUtils.java
  src/main/java/trend_setter/turtlerun/user/jwt/TokenProvider.java
  src/main/java/trend_setter/turtlerun/user/jwt/TokenValidator.java
  src/main/java/trend_setter/turtlerun/user/service/CookieService.java
  src/main/java/trend_setter/turtlerun/user/service/CustomAuthenticationProvider.java
  src/main/java/trend_setter/turtlerun/user/service/CustomUserDetailsService.java
  src/main/java/trend_setter/turtlerun/user/service/JwtAuthenticationService.java
  src/main/java/trend_setter/turtlerun/user/service/UserService.java
Labels: 🔨 Refactor

#89 [Fix] createdAt, updatedAt 값 자동 설정
  src/main/java/trend_setter/turtlerun/TurtleRunApplication.java
Labels: 🐛 Bug Fix

#92 [Feat] 이메일 인증 구현
  build.gradle
  src/main/java/trend_setter/turtlerun/global/config/MailConfig.java
  src/main/java/trend_setter/turtlerun/global/config/SecurityConfig.java
  src/main/java/trend_setter/turtlerun/user/controller/UserController.java
  src/main/java/trend_setter/turtlerun/user/dto/MemberEmailVerifiedResponse.java
  src/main/java/trend_setter/turtlerun/user/dto/RegisterUserRequest.java
  src/main/java/trend_setter/turtlerun/user/entity/User.java
  src/main/java/trend_setter/turtlerun/user/jwt/JwtAuthenticationFilter.java
  src/main/java/trend_setter/turtlerun/user/jwt/JwtUtils.java
  src/main/java/trend_setter/turtlerun/user/jwt/TokenValidator.java
  src/main/java/trend_setter/turtlerun/user/service/MailService.java
  src/main/java/trend_setter/turtlerun/user/service/UserService.java
Labels: ✨ Feature

#94 [Feat] 닉네임, 비밀번호 변경 기능 구현
  src/main/java/trend_setter/turtlerun/user/controller/UserController.java
  src/main/java/trend_setter/turtlerun/user/dto/ChangeNicknameRequest.java
  src/main/java/trend_setter/turtlerun/user/dto/ChangePasswordRequest.java
  src/main/java/trend_setter/turtlerun/user/entity/User.java
  src/main/java/trend_setter/turtlerun/user/repository/UserRepository.java
  src/main/java/trend_setter/turtlerun/user/service/UserService.java
Labels: ✨ Feature

#96 [Feat] 회원 정지 처리 메서드 구현
  src/main/java/trend_setter/turtlerun/user/dto/ChangeNicknameRequest.java
  src/main/java/trend_setter/turtlerun/user/dto/ChangePasswordRequest.java
  src/main/java/trend_setter/turtlerun/user/dto/LoginRequest.java
  src/main/java/trend_setter/turtlerun/user/dto/LoginResponse.java
  src/main/java/trend_setter/turtlerun/user/dto/MemberEmailVerifiedResponse.java
  src/main/java/trend_setter/turtlerun/user/dto/RegisterUserRequest.java
  src/main/java/trend_setter/turtlerun/user/dto/UserResponseDto.java
  src/main/java/trend_setter/turtlerun/user/entity/User.java
  src/main/java/trend_setter/turtlerun/user/service/UserService.java
Labels: ✨ Feature

#98 [Refactor] SecurityConfig 수정
  src/main/java/trend_setter/turtlerun/global/config/SecurityConfig.java
Labels: 🔨 Refactor

#99 [Feat] CI/CD docker/login-action v2 -> v3
  .github/workflows/deploy.yml
  .github/workflows/pr-check.yml
Labels: 🔄 CI/CD

#102 [Feat] 회원 탈퇴 기능 구현
  src/main/java/trend_setter/turtlerun/global/config/SecurityConfig.java
  src/main/java/trend_setter/turtlerun/user/constant/Role.java
  src/main/java/trend_setter/turtlerun/user/controller/UserController.java
  src/main/java/trend_setter/turtlerun/user/entity/User.java
  src/main/java/trend_setter/turtlerun/user/service/UserService.java
Labels: ✨ Feature

#104 [Feat] 회원 탈퇴 취소 기능 구현
  src/main/java/trend_setter/turtlerun/global/config/SecurityConfig.java
  src/main/java/trend_setter/turtlerun/user/controller/UserController.java
  src/main/java/trend_setter/turtlerun/user/entity/User.java
  src/main/java/trend_setter/turtlerun/user/service/UserService.java
Labels: ✨ Feature

#106 [Feat] 문의하기 화면 1차 구현
  frontend/src/app/inquiry/[id]/layout.tsx
  frontend/src/app/inquiry/[id]/page.tsx
  frontend/src/app/inquiry/[id]/response/layout.tsx
  frontend/src/app/inquiry/[id]/response/page.tsx
  frontend/src/app/inquiry/layout.tsx
  frontend/src/app/inquiry/new/layout.tsx
  frontend/src/app/inquiry/new/page.tsx
  frontend/src/app/inquiry/page.tsx
  frontend/src/components/inquiry/InquiryDetail.tsx
  frontend/src/components/inquiry/InquiryForm.tsx
  frontend/src/components/inquiry/InquiryList.tsx
Labels: ✨ Feature, 💄 FE
