Repository turt1eRun/turtle-run, pull requests merged in 2024-12, with the labels that each got.

#109 [Feat] 회원 정보 자동 삭제 구현
  src/main/java/trend_setter/turtlerun/user/entity/User.java
  src/main/java/trend_setter/turtlerun/user/repository/UserRepository.java
  src/main/java/trend_setter/turtlerun/user/service/UserService.java
Labels: ✨ Feature

#112 [Feat] 동영상 재업로드 기능 구현
  src/main/java/trend_setter/turtlerun/content/controller/ContentController.java
  src/main/java/trend_setter/turtlerun/content/dto/GetContentResponse.java
  src/main/java/trend_setter/turtlerun/content/dto/ModifyContentVideoRequest.java
  src/main/java/trend_setter/turtlerun/content/entity/Content.java
  src/main/java/trend_setter/turtlerun/content/service/ContentService.java
  src/main/java/trend_setter/turtlerun/content/service/DescriptionService.java
  src/main/java/trend_setter/turtlerun/content/service/ThumbnailService.java
  src/main/java/trend_setter/turtlerun/global/config/BatchConfig.java
  src/main/java/trend_setter/turtlerun/global/infra/s3/service/S3SimpleUploader.java
  src/test/java/trend_setter/turtlerun/global/config/BatchConfigTest.java
Labels: ✨ Feature, ⚙️ BE

#114 [Feat] 컨텐츠 업로드 화면 구현
  frontend/next.config.ts
  frontend/src/app/content/layout.tsx
  frontend/src/app/content/new/edit/page.tsx
  frontend/src/app/content/new/page.tsx
  frontend/src/components/common/Sidebar.tsx
  frontend/src/components/content/VideoUploader.tsx
  frontend/src/components/content/edit/BlockComponent.tsx
  frontend/src/components/content/edit/ContentEditor.tsx
  frontend/src/components/content/edit/ThumbnailUploader.tsx
  frontend/src/components/content/edit/VideoPreview.tsx
  frontend/src/hooks/useContentForm.ts
  frontend/src/lib/api/content.ts
  frontend/src/types/content.ts
  src/main/java/trend_setter/turtlerun/content/dto/GetFileResponse.java
  src/main/java/trend_setter/turtlerun/content/entity/Content.java
  src/main/java/trend_setter/turtlerun/content/entity/DescriptionFile.java
  src/main/java/trend_setter/turtlerun/content/entity/ThumbnailFile.java
  src/main/java/trend_setter/turtlerun/content/entity/VideoFile.java
  src/main/java/trend_setter/turtlerun/content/repository/DescriptionFileRepository.java
  src/main/java/trend_setter/turtlerun/content/repository/ThumbnailFileRepository.java
  src/main/java/trend_setter/turtlerun/content/repository/VideoFileRepository.java
  src/main/java/trend_setter/turtlerun/content/service/DescriptionService.java
  src/main/java/trend_setter/turtlerun/content/service/FileDeleteScheduler.java
  src/main/java/trend_setter/turtlerun/content/service/ThumbnailService.java
  src/main/java/trend_setter/turtlerun/content/service/VideoService.java
  src/main/java/trend_setter/turtlerun/global/config/BatchConfig.java
  src/main/java/trend_setter/turtlerun/global/infra/s3/service/S3VideoUploader.java
  src/main/java/trend_setter/turtlerun/user/jwt/JwtAuthenticationFilter.java
  src/test/java/trend_setter/turtlerun/global/infra/s3/service/S3VideoUploaderTest.java
Labels: ✨ Feature, 💄 FE
